# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.12.0-stretch
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/TheRek

    steps:
      - checkout

      ## FRONTEND TESTS

      # restore frontend node_modules
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "frontend/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cd frontend && yarn install

      - save_cache:
          paths:
            - frontend/node_modules
          key: v1-dependencies-{{ checksum "frontend/package.json" }}
        
      # lint frontend
      - run: cd frontend && yarn lint

      ## BACKEND TESTS

      # restore backend node_modules
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "backend/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cd backend && yarn install

      - save_cache:
          paths:
            - backend/node_modules
          key: v1-dependencies-{{ checksum "backend/package.json" }}
        
      # lint backend
      - run: cd backend && yarn lint




