const USER_LOGIN = 'USER_LOGIN';
const BERRY_DARK_RED = '#692536';
const BERRY_BLUE = '#c8e2f0';
const BERRY_LIGHT_BLUE = '#eef7fb';
const BERRY_DARK_BLUE = '#1e212e';
const BERRY_MAROON = '#261923';

export { USER_LOGIN, BERRY_BLUE, BERRY_LIGHT_BLUE, BERRY_DARK_BLUE, BERRY_DARK_RED, BERRY_MAROON };
